### ISSUE TITLE
Can't read the data from the database because the DB size is greater than `554.7 MB` 

### ISSUE THREAD

**Issue by Riken-Shah** [TomPrograms/stormdb#37]
First of all, I'd like to thank the creators and contributors of stormdb to create such an awesome local database.

Error when trying to read the database,
```
node:buffer:593
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:593:37)
    at Buffer.toString (node:buffer:811:14)
    at Object.readFileSync (node:fs:497:41)
    at LocalEngine.read (/home/ubuntu/scraper/node_modules/stormdb/src/engine/local.js:23:19)
    at LocalEngine.init (/home/ubuntu/scraper/node_modules/stormdb/src/engine/local.js:18:19)
    at new StormDB (/home/ubuntu/scraper/node_modules/stormdb/src/stormdb.js:5:30)
    at getDB (file:///home/ubuntu/scraper/localDB.js:5:10)
    at saveDataToMongoDB (file:///home/ubuntu/scraper/index.js:107:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (file:///home/ubuntu/scraper/index.js:211:3) {
  code: 'ERR_STRING_TOO_LONG'
}
```

**Comment by TomPrograms** [comment]
This is interesting. You appear to be hitting some in-built memory limits that I didn't consider in your version of Node.js. What version of Node.js are you using?

**Comment by Riken-Shah** [comment]
My version of node is `v16.13.2`.
